name: Daily Calendar Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install feedparser

    - name: Run Script
      run: python script.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "shubham-bot"
        git config --global user.email "bot@shubham.com"
        git add holidays.json
        git commit -m "🔄 Daily Holiday Auto-Update" || exit 0
        git push
